---
title: "CTA Final"
output:
  html_document: default
  word_document: default
date: "2024-04-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library("ggplot2")
library("plyr")
library("gdata")
library("stringr")
library("data.table")
library("stringi") 
library("dplyr") 
library("tidytext") 
library("kableExtra") 
library("babynames")
library("ggthemes")
library("patchwork")
```

```{r}
##Download the Data
data = fread("/Users/tyqtyq/Desktop/dataverse_files/uk_data.csv", encoding="UTF-8")
##There are 958925 obs(speeches) will be study
```

```{r}
#Check the colnames of the data set
colnames(data)
```

```{r}
##Data Preparation: (1)Creat the Time vriable for plotting trens 
data$time= NA
data$time[data$date>=as.Date("2001-01-01") & data$date<=as.Date("2001-06-30")] = "01/1"
data$time[data$date>=as.Date("2001-07-01") & data$date<=as.Date("2001-12-31")] = "01/2"
data$time[data$date>=as.Date("2002-01-01") & data$date<=as.Date("2002-06-30")] = "02/1"
data$time[data$date>=as.Date("2002-07-01") & data$date<=as.Date("2002-12-31")] = "02/2"
data$time[data$date>=as.Date("2003-01-01") & data$date<=as.Date("2003-06-30")] = "03/1"
data$time[data$date>=as.Date("2003-07-01") & data$date<=as.Date("2003-12-31")] = "03/2"
data$time[data$date>=as.Date("2004-01-01") & data$date<=as.Date("2004-06-30")] = "04/1"
data$time[data$date>=as.Date("2004-07-01") & data$date<=as.Date("2004-12-31")] = "04/2"
data$time[data$date>=as.Date("2005-01-01") & data$date<=as.Date("2005-06-30")] = "05/1"
data$time[data$date>=as.Date("2005-07-01") & data$date<=as.Date("2005-12-31")] = "05/2"
data$time[data$date>=as.Date("2006-01-01") & data$date<=as.Date("2006-06-30")] = "06/1"
data$time[data$date>=as.Date("2006-07-01") & data$date<=as.Date("2006-12-31")] = "06/2"
data$time[data$date>=as.Date("2007-01-01") & data$date<=as.Date("2007-06-30")] = "07/1"
data$time[data$date>=as.Date("2007-07-01") & data$date<=as.Date("2007-12-31")] = "07/2"
data$time[data$date>=as.Date("2008-01-01") & data$date<=as.Date("2008-06-30")] = "08/1"
data$time[data$date>=as.Date("2008-07-01") & data$date<=as.Date("2008-12-31")] = "08/2"
data$time[data$date>=as.Date("2009-01-01") & data$date<=as.Date("2009-06-30")] = "09/1"
data$time[data$date>=as.Date("2009-07-01") & data$date<=as.Date("2009-12-31")] = "09/2"
data$time[data$date>=as.Date("2010-01-01") & data$date<=as.Date("2010-06-30")] = "10/1"
data$time[data$date>=as.Date("2010-07-01") & data$date<=as.Date("2010-12-31")] = "10/2"
data$time[data$date>=as.Date("2011-01-01") & data$date<=as.Date("2011-06-30")] = "11/1"
data$time[data$date>=as.Date("2011-07-01") & data$date<=as.Date("2011-12-31")] = "11/2"
data$time[data$date>=as.Date("2012-01-01") & data$date<=as.Date("2012-06-30")] = "12/1"
data$time[data$date>=as.Date("2012-07-01") & data$date<=as.Date("2012-12-31")] = "12/2"
data$time[data$date>=as.Date("2013-01-01") & data$date<=as.Date("2013-06-30")] = "13/1"
data$time[data$date>=as.Date("2013-07-01") & data$date<=as.Date("2013-12-31")] = "13/2"
data$time[data$date>=as.Date("2014-01-01") & data$date<=as.Date("2014-06-30")] = "14/1"
data$time[data$date>=as.Date("2014-07-01") & data$date<=as.Date("2014-12-31")] = "14/2"
data$time[data$date>=as.Date("2015-01-01") & data$date<=as.Date("2015-06-30")] = "15/1"
data$time[data$date>=as.Date("2015-07-01") & data$date<=as.Date("2015-12-31")] = "15/2"
data$time[data$date>=as.Date("2016-01-01") & data$date<=as.Date("2016-06-30")] = "16/1"
data$time[data$date>=as.Date("2016-07-01") & data$date<=as.Date("2016-12-31")] = "16/2"
data$time[data$date>=as.Date("2017-01-01") & data$date<=as.Date("2017-06-30")] = "17/1"
data$time[data$date>=as.Date("2017-07-01") & data$date<=as.Date("2017-12-31")] = "17/2"
data$time[data$date>=as.Date("2018-01-01") & data$date<=as.Date("2018-06-30")] = "18/1"
data$time[data$date>=as.Date("2018-07-01") & data$date<=as.Date("2018-12-31")] = "18/2"
data$time[data$date>=as.Date("2019-01-01") & data$date<=as.Date("2019-06-30")] = "19/1"
data$time[data$date>=as.Date("2019-07-01") & data$date<=as.Date("2019-12-31")] = "19/2"

data$time2 = data$time
data$time2 = str_replace(data$time2, "/", "_")

data$stage = 0
data$stage[data$m_questions==1]= 1
data$stage[data$u_questions==1]= 2
data$stage[data$queen_debate_others==1]= 3
data$stage[data$queen_debate_day1==1]= 4
data$stage[data$pm_questions==1]= 5
```

```{r}
##Data Preparation: (2) get simplified dataset and select the variables which are related to the research questions
 data_simplified<- data %>%
  select(period, time, female, party, text, emotive_count, neutral_count, emotive_rhetoric, emotive_positive, emotive_negative)
##Check the new dataset
head(data_simplified)
```


```{r}
#Data Organization: #obs in the dataset with a value of "emotive rhetoric" greater than 0, i.e., the text used more emotional words, were filtered out to form a new dataset.
data_emotive <- data_simplified %>% 
  select(period, time, female, party, text, emotive_count, neutral_count, emotive_rhetoric, emotive_positive, emotive_negative) %>% 
  filter(emotive_rhetoric>0)
```

```{r}
###Data Organization:obs in the dataset with a value of "emotional rhetoric" less than 0, i.e., the text used more neutral words, were filtered out to form a new dataset.
data_neutral <- data_simplified %>% 
  select(period, time, female, party, text, emotive_count, neutral_count, emotive_rhetoric) %>% 
  filter(emotive_rhetoric<=0)
```

```{r}
##Term Frequency of Female-related words
## Word Frequency of Female-related Words in all data
#Since the complete dataset is too large, I first sample it
data_samp <- data_simplified %>%
  sample_n(10000)
```

```{r}
##Tidy the text
tokens_all <- data_samp %>%
  unnest_tokens(word, text)
head(tokens_all)
``` 
```{r}
## remove all stop words（the original dataset has removed all apostrophes)
tokens_all<- tokens_all %>%
    filter(!word %in% stop_words$word)
```

```{r}
##Assign a value of "1" to each obs for easy counting of quantities.
tokens_all <- tokens_all  %>%
  mutate(obs=1) 
```

```{r}
##Word Frequency Analysis: Calculating the number of female-related words in all texts(sampled)
tokens_all$womword <- as.integer(grepl("women|woman|female|girl|feminist|feminism|feminine|gender|harassment|sexism|sexist|lady|madam|womenlike|ladylike", x = tokens_all$word))
```

```{r}
## Word Frequency of Female-related Words in Texts Using Strongly Emotive Rhetoric
##Tidy the text
tokens_emo <- data_emotive %>%
  unnest_tokens(word, text)
head(tokens_emo)
``` 

```{r}
## remove all stop words（the original dataset has removed all apostrophes)
tokens_emo<- tokens_emo %>%
    filter(!word %in% stop_words$word)
```

```{r}
##Check the dataset
head(tokens_emo)
```

```{r}
##Get the number of women-related words  in all speeches through "filter" function
 all_women_counts <-tokens_all %>% 
   filter(womword==1)
 ##Check the new dataset (especially the number of obs)
 head(all_women_counts)
 ##There are 120404 obs in the new dataset
```

```{r}
##Assign a value of 1 to each observation for easy counting of quantities.
tokens_emo <- tokens_emo  %>%
  mutate(obs=1) 
```

```{r}
##Word Frequency Analysis: Calculating the number of female-related words in texts with high levels of emotive rhetoric
tokens_emo$womword <- as.integer(grepl("women|woman|female|girl|feminist|feminism|feminine|gender|harassment|sexism|sexist|lady|madam|womenlike|ladylike", x = tokens_emo$word))
```

```{r}
##Check the dataset
head(tokens_emo)
```


```{r}
##Get the number of women-related words  in these texts with stronger emotive rhetoric through "filter" function
 emo_women_counts <-tokens_emo %>% 
   filter(womword==1)
 ##Chect the obs of new dataset (especially the number of obs)
 head(emo_women_counts)
 ##There are 120404 obs in the new dataset
```


```{r}
## Word Frequency of Female-related Words in Texts Using More Neutral Words
##Tidy the text
tokens_neu <- data_neutral %>%
  unnest_tokens(word, text)
##Check the dataset
head(tokens_neu)
``` 

```{r}
## remove all stop words（the original dataset has removed all apostrophes)
tokens_neu<- tokens_neu %>%
    filter(!word %in% stop_words$word)
```

```{r}
##Assign a value of 1 to each observation for easy counting of quantities.
tokens_neu <- tokens_neu  %>%
  mutate(obs=1) 
```


```{r}
##Word Frequency Analysis: Calculating the number of female-related words in texts with equal or more neutral words
tokens_neu$womword <- as.integer(grepl("women|woman|female|girl|feminist|feminism|feminine|gender|harassment|sexism|sexist|lady|madam|womenlike|ladylike", x = tokens_neu$word))
```

```{r}
##Check the dataset
head(tokens_neu)
```

```{r}
##Get the number of women-related words  in these texts with equal or more neutral words through "filter" function
 neu_women_counts <-tokens_neu %>% 
   filter(womword==1)
 ##Chect the obs of new dataset (especially the number of obs)
 head(neu_women_counts)
 ##There are 53371 obs in the new dataset
```
 
```{r}
##Time Trends
##Exploring Temporal Trends in Female-Related Words in all sampled data
##Calculate the total number of words and the number of female-related words for different time
women_counts_time<- tokens_all %>%
  group_by(time) %>%
  mutate(time_total = sum(obs)) %>% ## "n" in the original data is closure, so I decided to sum obs.
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),
            time_total= min(time_total))
```

```{r}
head(women_counts_time)
```

```{r}
##plot the results to show the trend of time
ggplot(women_counts_time, aes(time, sum_wom / time_total, group=1)) +
  geom_line() +
  xlab("Time") +
  ylab("female-related words frequency") +
  scale_y_continuous(labels = scales::percent_format(),
                     expand = c(0, 0), limits = c(0, NA)) +
  theme_tufte(base_family = "Helvetica") +
 theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels by 45 degrees
```

```{r}
##Exploring Temporal Trends in Female-Related Vocabulary in Texts with Strong Levels of Emotive Rhetoric
##Calculate the total number of words and the number of female-related words for different time
tokens_emo_time <- tokens_emo %>%
  group_by(time) %>%
  mutate(time_total = sum(obs)) %>% ## "n" in the original data is closure, so I decided to sum obs.
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),
            time_total= min(time_total))
```

```{r}
head(tokens_emo_time)
```

```{r}
##plot the results to show the trend of time
ggplot(tokens_emo_time, aes(time, sum_wom / time_total, group=1)) +
  geom_line(color = "blue") +
  xlab("Time") +
  ylab("% female-related words") +
  scale_y_continuous(labels = scales::percent_format(),
                     expand = c(0, 0), limits = c(0, NA)) +
  theme_tufte(base_family = "Helvetica") +
theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels by 45 degrees
```


```{r}
##Exploring Temporal Trends in Female-Related Vocabulary in Texts with Emotive Rhetoric Scores no more than 0
##Calculate the total number of words and the number of female-related words for different time
tokens_neu_time <- tokens_neu %>%
  group_by(time) %>%
  mutate(time_total = sum(obs)) %>%
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),
            time_total= min(time_total))
```

```{r}
##Check the dataset
head(tokens_neu_time)
```

```{r}
##plot the results to show the trend of time
ggplot(tokens_neu_time, aes(time, sum_wom / time_total, group=1)) +
  geom_line(color = "red") +
  xlab("Time") +
  ylab("female-related words frenquency") +
  scale_y_continuous(labels = scales::percent_format(),
                     expand = c(0, 0), limits = c(0, NA)) +
  theme_tufte(base_family = "Helvetica") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels by 45 degrees
```
```{r}
##Combine two plots into one for the easier comparison
combined_plot <- ggplot() +
  geom_line(data = tokens_emo_time, aes(time, sum_wom / time_total, group = 1, color = "emotive")) +
  geom_line(data = tokens_neu_time, aes(time, sum_wom / time_total, group = 1, color = "neutral")) +
  labs(title = "Combined Line Plot", x = "Time", y = "female-related words frequency")+
  theme_minimal()+
theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
##Check the plot
print(combined_plot)
```


```{r}
##Trends across Five Election Periods
##Exploring Five Election Trends of Female-Related words in all sampled data
##Calculate the total number of words and the number of female-related words for different period
women_counts_period<- tokens_all %>%
  group_by(period) %>%
  mutate(period_total = sum(obs)) %>% ## "n" in the original data is closure, so I decided to sum obs.
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),
            period_total= min(period_total))
```

```{r}
##Check the Data
head(women_counts_period)
```

```{r}
##plot the results to show the trend of period
ggplot(women_counts_period, aes(period, sum_wom / period_total, group=1)) +
  geom_line() +
  xlab("election period") +
  ylab("female-related words frequency") +
  scale_y_continuous(labels = scales::percent_format(),
                     expand = c(0, 0), limits = c(0, NA)) +
  theme_tufte(base_family = "Helvetica") +
 theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels by 45 degrees
```

```{r}
#Exploring Five Election Trends of Female-Related words in texts with high level of emotive rhetoric
##Calculate the total number of words and the number of female-related words for different period
emo_counts_period<- tokens_emo %>%
  group_by(period) %>%
  mutate(period_total = sum(obs)) %>% ## "n" in the original data is closure, so I decided to sum obs.
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),
            period_total= min(period_total))
```

```{r}
##Check the Data
head(emo_counts_period)
```
```{r}
##plot the results to show the trend of period
ggplot(emo_counts_period, aes(period, sum_wom / period_total, group=1)) +
  geom_line(color = "blue") +
  xlab("election period") +
  ylab("female-related words freuquency") +
  scale_y_continuous(labels = scales::percent_format(),
                     expand = c(0, 0), limits = c(0, NA)) +
  theme_tufte(base_family = "Helvetica") +
 theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels by 45 degrees
```

```{r}
###Exploring Five Election Trends of Female-Related words in texts with more neutral words
##Calculate the total number of words and the number of female-related words for different period
neu_counts_period <- tokens_neu %>%
  group_by(period) %>%
  mutate(period_total = sum(obs)) %>% ## "n" in the original data is closure, so I decided to sum obs.
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),
            period_total= min(period_total))
```

```{r}
head(neu_counts_period)
```

```{r}
##plot the results to show the trend of period
ggplot(neu_counts_period, aes(period, sum_wom / period_total, group=1)) +
  geom_line(color = "red") +
  xlab("election period") +
  ylab("female-related words freuquency") +
  scale_y_continuous(labels = scales::percent_format(),
                     expand = c(0, 0), limits = c(0, NA)) +
  theme_tufte(base_family = "Helvetica") +
 theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels by 45 degrees
```

```{r}
##Combine two plots into one for the easier comparison
combined_plot_period <- ggplot() +
  geom_line(data = emo_counts_period, aes(period, sum_wom / period_total, group = 1, color = "emotive")) +
  geom_line(data = neu_counts_period, aes(period, sum_wom / period_total, group = 1, color = "neutral")) +
  labs(title = "Combined Line Plot for Five Election Period", x = "period", y = "female-related words frequency")+
  theme_minimal()+
theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
##Check the plot
print(combined_plot_period)
```



```{r}
## Match female-related word frequency in all sampled texts and different party 
##Calculate the total number of words and the number of female-related words for different party
party_counts <- tokens_all %>%
  group_by(party) %>%
  mutate(party_total = sum(obs)) %>%
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),
            party_total= min(party_total))
```

```{r}
##Check the dataset
head(party_counts)
```

```{r}
##plot the results
ggplot(party_counts, aes(x = party, y = sum_wom / party_total)) +
 geom_bar(stat = "identity", fill = "skyblue") +  # Create bars
  labs(x = "party", y = "female-related word frequency") +  # Labels
  theme_minimal() +  # Minimal theme
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels by 45 degrees
```


```{r}
## Match female-related word frequency in texts which have higer level of emotive rhetoric and party in UK
##Calculate the total number of words and the number of female-related words for different party
emo_party_counts <- tokens_emo %>%
  group_by(party) %>%
  mutate(party_total = sum(obs)) %>%
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),
            party_total= min(party_total))
```

```{r}
head(emo_party_counts)
```

```{r}
##plot the results
ggplot(emo_party_counts, aes(x = party, y = sum_wom / party_total)) +
 geom_bar(stat = "identity", fill = "skyblue") +  # Create bars
  labs(x = "party", y = "female-related word frequency") +  # Labels
  theme_minimal() +  # Minimal theme
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels by 45 degrees       party_total= min(party_total))
```

```{r}
## Match female-related word frequency in texts which have more neutral words and different party
##Calculate the total number of words and the number of female-related words for different party
neu_party_counts <- tokens_neu %>%
  group_by(party) %>%
  mutate(party_total = sum(obs)) %>%
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),
            party_total= min(party_total))
```

```{r}
##plot the results
ggplot(neu_party_counts, aes(x = party, y = sum_wom / party_total)) +
 geom_bar(stat = "identity", fill = "skyblue") +  # Create bars
  labs(x = "party", y = "female-related word frequency") +  # Labels
  theme_minimal() +  # Minimal theme
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels by 45 degrees
```

```{r}
## Match female-related word frequency in all sampled texts rhetoric and gender of speakers
##Calculate the total number of words and the number of female-related words for different gender
gender_counts <- tokens_all %>%
  group_by(female) %>%
  mutate(gender_total = sum(obs)) %>%
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),gender_total= min(gender_total))
```



```{r}
##Make the continuous variable “female”, from “0” and “1” to the categorical variables “male” and “female”
gender_counts <- gender_counts %>% 
  mutate(Gender = c("Male", "Female"),
         female = c(0, 1))
```

```{r}
#Check the dataset
head(gender_counts)
```


```{r}
##plot the results
ggplot(gender_counts, aes(x = Gender, y = sum_wom / gender_total)) +
 geom_bar(stat = "identity", fill = "skyblue") +  # Create bars
  labs(x = "Gender", y = "female-related word frequency") +  # Labels
  theme_minimal() 
```


```{r}
## Match female-related word frequency in texts wich have higer level of emotive rhetoric and gender of speakers
##Calculate the total number of words and the number of female-related words for different gender
emo_gender_counts <- tokens_emo %>%
  group_by(female) %>%
  mutate(gender_total = sum(obs)) %>%
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),gender_total= min(gender_total))
```

```{r}
head(emo_gender_counts)
## "0" means male and "1" means female
```

```{r}
##Make the continuous variable “female”, from “0” and “1” to the categorical variables “male” and “female”.
emo_gender_counts <- emo_gender_counts %>% 
  mutate(Gender = c("Male", "Female"),
         female = c(0, 1))
```

```{r}
##Check the dataset
head(emo_gender_counts)
```

```{r}
##plot the results
ggplot(emo_gender_counts, aes(x = Gender, y = sum_wom / gender_total)) +
 geom_bar(stat = "identity", fill = "skyblue") +  # Create bars
  labs(x = "Gender", y = "female-related word frequency") +  # Labels
  theme_minimal() 
```

```{r}
## Match female-related word frequency in texts which have emotive rhetoric scores no more than 0 and the gender of speakers
##Calculate the total number of words and the number of female-related words for different gender
neu_gender_counts <- tokens_neu %>%
  group_by(female) %>%
  mutate(gender_total = sum(obs)) %>%
  filter(womword==1) %>%
  summarise(sum_wom = sum(obs),gender_total= min(gender_total))
```

```{r}
##Make the continuous variable “female”, from “0” and “1” to the categorical variables “male” and “female”.
neu_gender_counts <- neu_gender_counts %>% 
  mutate(Gender = c("Male", "Female"),
         female = c(0, 1))
```

```{r}
##Check the dataset
head(neu_gender_counts)
```
```{r}
##plot the results
ggplot(neu_gender_counts, aes(x = Gender, y = sum_wom / gender_total)) +
 geom_bar(stat = "identity", fill = "skyblue") +  # Create bars
  labs(x = "Gender", y = "female-related word frequency") +  # Labels
  theme_minimal() 
```